### ISSUE TITLE
[Question]: Would ember-cli-update also update the `scripts` path in package.json?

### ISSUE THREAD

**Issue by abhilashlr** [ember-cli/ember-cli-update#1040]
While trying to do ember-cli-update to 3.17.0 or 3.18.0-beta.0, the `scripts` attribute doesn't seem to get the updates of https://github.com/ember-cli/ember-cli/blob/v3.18.0-beta.1/blueprints/app/files/package.json#L13

```
"scripts": {
    "build": "ember build --environment=production",
    "lint": "npm-run-all --aggregate-output --continue-on-error --parallel lint:*",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "npm-run-all lint:* test:*",
    "test:ember": "ember test"
  },
```
Should this also be part of the ember-cli-update command?

```
"ember-cli": "~3.17.0",
"ember-cli-update": "^0.54.6",
```

**Comment by kellyselden** [comment]
It depends what existing version you are on, and if the scripts changes happened between the two. If you are on a newer ember-cli version than when the scripts change happened, you'll need to `ember init` or `ember-cli-update init` to get it back.

**Comment by abhilashlr** [comment]
The ember-cli version was 3.17.0 and then I migrated to 3.18-beta.1. But neither did it occur while I migrated from 3.17-beta.0 to 3.17.

**Comment by kellyselden** [comment]
You can check ember-new-output to see when the change occured.
