### ISSUE TITLE
Cannot select blueprints update with arrow keys

### ISSUE THREAD

**Issue by sandstrom** [ember-cli/ember-cli-update#1104]
I can't select a blueprints update with the arrow keys.

> Blueprint updates have been found. Which one would you like to update? app, current: 3.22.0, latest: 3.24.0

Maybe related to this issue:

https://github.com/SBoudrias/Inquirer.js/issues/844

Perhaps a work-around would be to use/allow some other input method, e.g. numbers?

Something like this:
https://github.com/SBoudrias/Inquirer.js/#expand---type-expand

**Comment by kellyselden** [comment]
It looks like you only have one blueprint to select?

**Comment by sandstrom** [comment]
Console output looks like this:

![image](https://user-images.githubusercontent.com/122287/105214227-04bdf000-5b50-11eb-8b95-0aa718d403c8.png)

I would have guessed at three options, but maybe I'm missing something.

**Comment by kellyselden** [comment]
correct. its just helpful metadata.

**Comment by sandstrom** [comment]
thanks @kellyselden 😄
