### ISSUE TITLE
Don't overwrite README.md

### ISSUE THREAD

**Issue by CodePolymath** [ember-cli/ember-cli-update#1215]
Seems pretty straightforward, and I'm honestly frustrated that you all thought it was OK to completely wipe and rewrite my entire README.md file. Your code took all the instructions and information I carefully put into my project's README.md file and replaced them with generic BS like _"A short introduction of this app could easily go here."_ Guess what? I already WROTE a description... you deleted it!

Please respect your users and don't wipe their README.md files, thanks.

**Comment by bertdeblock** [comment]
`ember-cli-update` applies the changes between your current version of `ember-cli` and the version you are updating to. Indeed, it modifies files, that's just how this tool works and is also clearly mentioned in the docs.
Most likely, you would've had merge conflicts on your `README.md` file, which you should've been able to resolve manually. If your code is versioned, I don't really see the issue?

**Comment by CodePolymath** [comment]
[bertdeblock](https://github.com/bertdeblock) tools are supposed to make coding easier, not more complicated.
