### ISSUE TITLE
yarn projects don't get clean diffs

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-update#125]
the output repos only record the standard blueprint, not the yarn variant or any others. Projects using a variant will get weird conflicts.

I don't know if there is a sane way to fix this.

**Comment by kellyselden** [comment]
The best I can come up with is if we ship changesets with ember-cli. @rwjblue @kategengler thoughts?

**Comment by kategengler** [comment]
The only other thing I can think of is output repos for every possible combination of variants.
