### ISSUE TITLE
Created an es5-getter-ember-codemod that might be a good addition

### ISSUE THREAD

**Issue by rondale-sc** [ember-cli/ember-cli-update#255]
This codemod is intended to automatically convert your usage of get, and getProperties to use traditional object dot notation as proposed by [emberjs/rfcs#281](https://github.com/emberjs/rfcs/blob/master/text/0281-es5-getters.md).

https://github.com/rondale-sc/es5-getter-ember-codemod

**Comment by kellyselden** [comment]
Definitely lets add this. We have minimum version support, so you can add it now with minimum version 3.2, which I believe is the correct version minimum.

**Comment by rwjblue** [comment]
3.1 is where the feature was introduced...

**Comment by rondale-sc** [comment]
@kellyselden I'll put this on my TODO list for tomorrow.
