### ISSUE TITLE
Quest: Update official documentation

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-update#288]
Now that this is the official way to update ember apps, we need to have all traces of any previous processes updated. These include:

- [x] ember-cli.com https://github.com/ember-cli/ember-cli.github.io/pull/210
- [ ] ember-cli changelog
- [ ] ember-cli release notes
- [ ] ember.js release blog post

Anything I've missed? @locks has offered to help guide this ship as well.

**Comment by KamiKillertO** [comment]
What should we do?

**Comment by jenweber** [comment]
@kellyselden I think the builds app should link to instructions for upgrading and install, but it doesn't yet contain that info.

**Comment by KamiKillertO** [comment]
The upgrade section on ember-cli.com has been updated (https://ember-cli.com/user-guide/#upgrading)

**Comment by kellyselden** [comment]
This may help https://github.com/ember-cli/ember-cli-update/pull/343

**Comment by kellyselden** [comment]
I think this is done now.
