### ISSUE TITLE
show a "new version" message

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-update#326]
There a lots of utils that will do this for us.

**Comment by jessica-jordan** [comment]
Would this be a message that is shown to the user anytime they use ember-cli-update?

**Comment by kellyselden** [comment]
I think so.

**Comment by dbbk** [comment]
Not sure I follow the flow here, if someone is using `ember-cli-update` won't they already know about a new version or be intending to upgrade to it? Surely a message on `ember build` or `ember serve` would be a better place.

**Comment by astronomersiva** [comment]
I believe you are looking for something like this?

https://github.com/yeoman/update-notifier

This is used by NPM(among others) to display the small banner like message on the terminal when a new version is available. I am interested in taking a jab at this if this looks good to you.

**Comment by kellyselden** [comment]
Yes. I am interested in using the most industry standard solution to this problem.

**Comment by astronomersiva** [comment]
I have raised a PR for this.

As a sidenote, won't running `npx ember-cli-codemod` always run the latest version? Maybe we can add that to the docs as well? I prefer using npx instead of having to install globally.

**Comment by kellyselden** [comment]
This is now done #344
