### ISSUE TITLE
Feature - Validate npm package app name as part of updating?

### ISSUE THREAD

**Issue by jenweber** [ember-cli/ember-cli-update#336]
**Current behavior:**
If your app is named something weird like `@organization/my-app-name` in package.json, upgrading Ember versions can result in some unexpected behavior. It seems that ember-cli build uses the app name in `package.json` in a way that it didn't before, and I wonder if this tool should have a feature to catch issues like that.

**Error behavior**
After upgrading from 2.12-->2.18, we got `Failed to load resource: the server responded with a status of 404 (Not Found)` for `my-app-name.js`. That file actually ended up in `dist/assets/@organization/my-app-name.js` because our app's name in package.json was `@organization/my-app-name`

**Possible feature**
Check package.json to make sure the name is valid as part of the upgrade process. I'm not sure if this is worth adding as a feature because it might be a super-edge-case-y. I'm not sure how common it is to give apps scoped names. It's not something that ever occurred to me to do, but one of my coworkers made the change at some point.

Feel free to close if this is outside of the scope of the tool or a rare problem.

❤️ this tool, so much nicer than `init`

**Comment by kellyselden** [comment]
I think this could be handled in Ember CLI as a warning, or by an external codemod that could be bundled in this app. Let me know if I'm wrong.
