### ISSUE TITLE
running with codemod flag doesn't upgrade the project properly

### ISSUE THREAD

**Issue by gokatz** [ember-cli/ember-cli-update#338]
I don't know if it is the actual behaviour. When running the update command with `--run-codemods` option, the `ember init` like actions are not performed. Only the codemods were performed.

command: `ember-cli-update --run-codemods`

**Comment by kellyselden** [comment]
This is correct. You cannot run update and run codemods at the same time. Any documentation updates to make this more clear are welcome.
