### ISSUE TITLE
Ember CLI project type could not be determined

### ISSUE THREAD

**Issue by momohuri** [ember-cli/ember-cli-update#379]
Hi,
I am trying to update y project but I am getting this:
```
DEBUG=ember-cli-update,git-diff-apply ember-cli-update
Ember CLI project type could not be determined
```
I am currently using : 
ember-cli: 3.2.0
node: 10.6.0
os: darwin x64

And I am at ember 2.18.0

Am I missing configuration file?

thanks

**Comment by mcfiredrill** [comment]
I had this same problem.

It looks like you get this error if you don't have ember-cli in your devDependencies in your package.json.
https://github.com/ember-cli/ember-cli-update/blob/master/src/get-project-type.js#L33

Maybe this error message could be improved? Or dependencies be checked as well?

**Comment by kellyselden** [comment]
An improved error message would be welcome and appreciated.

**Comment by matixmatix** [comment]
I'm also receiving this error, but `ember-cli-update` already is in my devDependencies. How can I solve this?

**Comment by kellyselden** [comment]
Fixed in https://github.com/ember-cli/ember-cli-update/pull/524.
