### ISSUE TITLE
ember-cli-update

### ISSUE THREAD

**Issue by adet4ever** [ember-cli/ember-cli-update#407]
Upon running ember-cli-update
for project update, I got the following message. My question is why is ember messing with my git?

I suppose it is trying to put me in a clean slate to test, however my project does depend on other projects which contents of the project's folder were deleted.

Cloning into bare repository '/tmp/tmp-3268421abpQXEkvA9/.git'...
Note: checking out '4104b96d8a1cdffb92b285f4cefce739f4a9843d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4104b96... 2.12.1
Previous HEAD position was 4104b96... 2.12.1
HEAD is now at 1463a1b... 3.3.0
Previous HEAD position was 1463a1b... 3.3.0
HEAD is now at 4104b96... 2.12.1
Previous HEAD position was 4104b96... 2.12.1
HEAD is now at 1463a1b... 3.3.0
Note: checking out '2126574c644989099d8071a34b57db43fc9ab069'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2126574... message
Switched to a new branch '625df500-ac86-11e8-960e-e3e6e4f00ca0'

**Comment by kellyselden** [comment]
Can you be more detailed with messing with your git please? Also, if things are getting deleted when they shouldn't, it may be this bug #143.

**Comment by adet4ever** [comment]
Well I guess when I tried the update for ember-cli since ember 1. The process never involve any anything to do with git. So I can say yesterday was the first time running  ember-cli-update (which clearly say you may have merge conflict --my bad)

For example, I would just run the following:

rm -rf node_modules dist tmp -- Delete temporary development folders.
npm install --save-dev ember-cli@3.2.0 -- Update project's package.json to use latest version.
npm install -- Reinstall NPM dependencies.
ember init -- This runs the new project blueprint on your projects directory. Please follow the prompts, and review all changes (tip: you can see a diff by pressing d). The most common source of upgrade pain is missing changes in this step.

Anyway I was surprised to see I was in detached Head state. and Giving that I need to 'clear' my git status (add uncommitted untracked files/folders)... I tried doing that and is when I realized that my rails project which is where I serve my ember-cli from is missing its app folder somehow. 

I have made some progress since yesterday by repeating the process and I think I am a bit ahead of where I was when I logged this report. It was just weird at the time...

**Comment by kellyselden** [comment]
Closing as I'm not sure how to move this forward. If there is a bug, please repost with more info.
