### ISSUE TITLE
Since ec-update needs to always be the latest version, should it update itself?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli-update#408]
I think this would be a neat way have the tool stay up-to-date.
Maybe it could print out some debug info about itself as you run commands with it.

**Comment by kellyselden** [comment]
You can use https://www.npmjs.com/package/npx to accomplish this.

**Comment by NullVoxPopuli** [comment]
is npx common?
I wonder if it'd be beneficial for yarn / npm to incorporate this. (I proxy most of my bins through yarn)

**Comment by kellyselden** [comment]
I'm not sure how common, but I use it all the time.

**Comment by NullVoxPopuli** [comment]
I'll take a look. thanks!
