### ISSUE TITLE
npm audit return lots of voulnerabilities in package

### ISSUE THREAD

**Issue by dzbo** [ember-cli/ember-cli-update#428]
I've recently been checking with `npm audit` tool and found that this package has a lot of issues

![Alt text](https://monosnap.com/image/EpAp72TjAOMzBc1z7umY9wbPPeqVLY.png)

So far the list has:
- https-proxy-agent
- sshpk
- tough-cookie

Any plans on fixing this?

**Comment by kellyselden** [comment]
I refreshed the lockfile and updated all the dependencies to the latest version, and they are still there. Not sure what else I can do, so closing.
