### ISSUE TITLE
--create-custom-diff doesn't seem to work with yarn

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli-update#436]
Is `ember-cli-update --create-custom-diff` all we need for it to work with yarn output?

**Comment by kellyselden** [comment]
I updated the readme to mention using your system .ember-cli file. If you put your yarn option in there, it should make a yarn diff.

**Comment by rwwagner90** [comment]
@kellyselden should it just be this?

```
{
  "yarn": true
}
```

We should probably be explicit about how to go about this.

**Comment by kellyselden** [comment]
I think the property is useYarn. I would love to link to docs about all the options available, but I'm not sure if that exists yet.

**Comment by rwwagner90** [comment]
@kellyselden I think `"yarn": true` made it work. We should determine what is correct and document it though.
