### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-cli-update#455]
I'd like to make a video soon showing us upgrading EmberMap's codebase, and we'll be using Ember CLI Update. I have a question about proper usage:

I think after we spoke at EmberCamp, my understanding was that we first run `ember-cli-update` and then `--run-codemods` on a second run, so that that upgrade and the codemods are done separately. That way, if there's a bug in the codemods, it would surface separately from a bug related to dependency updates.

What I can't remember is if the recommendation is to get the upgrade fully functioning with the dependency upgrades, including tests passing. My confusion here is, when upgrading from (say) 2.18 to 3.5, there's a lot of failing tests due to lint failures, which the codemods would help fix. So, it's tempting to want to run the codemods to help get the tests passing again.

What's the recommendation here?

**Comment by samselikoff** [comment]
Another question. The first time I run `ember-cli-update` I get

```
HEAD is now at fb844d2 2.17.0
Previous HEAD position was fb844d2 2.17.0
HEAD is now at 1bcb7a1 2.18.2
Previous HEAD position was 1bcb7a1 2.18.2
HEAD is now at fb844d2 2.17.0
Switched to a new branch 'c0807740-f491-11e8-b21e-cfbf6a666c9f'
Switched to branch 'upgrade-ember-cli-v2'
error: could not apply 312f897... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
Error: dest already exists.
    at pathExists (/Users/samselikoff/.npm/_npx/48212/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/Users/samselikoff/.npm/_npx/48212/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
    at <anonymous>
```

I fixed the conflicts, but then noticed `ember-cli` hadn't actually been changed in `package.json`. So I ran the command again. It marked the same files as conflicts (along with one new one) and then actually changed `package.json`.

Is this all expected, and if so could you explain why two runs were needed?

**Comment by kellyselden** [comment]
Unfortunately, from a documentation point of view, all version upgrades are not considered equal. While I would recommend fixing your tests before running codemods, depending on what versions you're jumping between, that is not the best approach.

As for the bug, I haven't seen that before. Can you reproduce on the latest version?

**Comment by samselikoff** [comment]
> While I would recommend fixing your tests before running codemods, depending on what versions you're jumping between, that is not the best approach.

Could you elaborate? Are you just saying, if you have a ton of rote/boilerplate code to change, running the Codemod before fixing the test might be ideal?

What about, ignoring linting, fixing the tests, and then running codemods, and then dealing with the full test suite?

**Comment by samselikoff** [comment]
> As for the bug, I haven't seen that before. Can you reproduce on the latest version?

Yep, just checked. Here's the full output:

```
➜  ember-map-frontend git:(ember-cli-update-bug) ember-cli-update
Cloning into bare repository '/var/folders/v5/5bs4trnx5v7bly3f0cg4_sc40000gn/T/tmp-797989DeICC77I5QC/.git'...
Note: checking out 'fb844d27aa65ee833e0a36a0cc8b0d79b7ee7a4a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you maydo so (now or later) by using -b with the checkout command again. Example:  git checkout -b <new-branch-name>
HEAD is now at fb844d2 2.17.0
Previous HEAD position was fb844d2 2.17.0
HEAD is now at cebcae7 3.5.1
Previous HEAD position was cebcae7 3.5.1
HEAD is now at fb844d2 2.17.0
Switched to a new branch '3e8fb320-f56f-11e8-8109-2fb482d658e7'
Switched to branch 'ember-cli-update-bug'
error: could not apply e78d6c8... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
```

**Comment by drevets** [comment]
I'm also getting the same error — if I run ember-cli-update multiple times then it eventually works: 

Cloning into bare repository '/var/folders/33/xcggwmhx33j5vvgfhjk4cl2w0000gp/T/tmp-24138E4q7x6XZ6aPE/.git'...
Note: checking out '8e3bbcaad3d40fe1ad03b649ed69cf4a569cbfb6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8e3bbca 2.18.1
Previous HEAD position was 8e3bbca 2.18.1
HEAD is now at cebcae7 3.5.1
Previous HEAD position was cebcae7 3.5.1
HEAD is now at 8e3bbca 2.18.1
Switched to a new branch '4588be20-fd84-11e8-911f-05842cf08bbd'
Switched to branch 'feature/RMA-545-ember-upgrade'
error: could not apply ab9bb2265... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
Error: dest already exists.
    at pathExists (/Users/edrevet/.nvm/versions/node/v8.12.0/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/Users/edrevet/.nvm/versions/node/v8.12.0/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
    at <anonymous>

**Comment by Subtletree** [comment]
Also getting the same with latest ember-cli-update

```
Cloning into bare repository '/var/folders/z_/ymrn00sn7vbg9sr7ytjggn5m0000gn/T/tmp-23474CS2LsQ4ovYcO/.git'...
Note: checking out '1f612533c12dfe8cc669787f2fede2a18afa062f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1f61253... 3.4.3
Previous HEAD position was 1f61253... 3.4.3
HEAD is now at cebcae7... 3.5.1
Previous HEAD position was cebcae7... 3.5.1
HEAD is now at 1f61253... 3.4.3
Switched to a new branch 'dd3d3e90-fdb0-11e8-b0fd-cf1dc78bb434'
Switched to branch 'master'
Error: dest already exists.
    at pathExists (/Users/ryanscott/.nvm/versions/node/v10.10.0/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/Users/ryanscott/.nvm/versions/node/v10.10.0/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
```

**Comment by kellyselden** [comment]
Tracking in https://github.com/ember-cli/ember-cli-update/issues/496
