### ISSUE TITLE
connect ETIMEDOUT 69.171.248.128:443

### ISSUE THREAD

**Issue by chenxu-javascript** [ember-cli/ember-cli-update#462]
when i run   ember-cli-update --run-codemods
`
{ Error: connect ETIMEDOUT 69.171.248.128:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '69.171.248.128',
  port: 443 }
`

how do i can resolve it

**Comment by kellyselden** [comment]
you may be having some connection issues to github or npm.
