### ISSUE TITLE
A monorepo causes the terminal to get into a bad state

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli-update#535]
I paired with @kellyselden to find what the cause of the issue was.

We determined that `ember-cli-update` quickly deletes the `ember` folder before adding it back. This appears to put terminal in a bad state where `ls` will indicate that the folder is empty and `git status` returns `fatal: Unable to read current working directory: No such file or directory`.

This seems to be an issue only caused when working with a monorepo.

**Comment by kellyselden** [comment]
Correct. It looks like it has the potential to temporarily delete whatever cwd/pwd is, and although the update succeeded, the terminal you have open stops responding to commands until you reopen it. I think this is fixable.
