### ISSUE TITLE
support arbitrary unversioned blueprints (-b option in ember-cli)

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-update#546]
@wycats mentioned it would be nice to update https://github.com/tildeio/libkit using this tool. This would also benifit the octane blueprint before it becomes official.

The first problem is ember-cli does not support npm versions other than latest for the blueprint. `ember new -b libkit@0.7.0-beta.1 libkit` does not work. The second is, there needs to be a stored-on-disk way for a blueprint's version to be looked up in your project. One suggestion could be

```js
// .ember-cli
{
  "ember-cli-update": {
    "blueprint": "libkit",
    "version": "0.7.0-beta.1"
  }
}
```

With those two problems solved, we can generate a diff between two versions of a blueprint.

**Comment by gabrielgrant** [comment]
Thanks a ton for working on this, it makes blueprints way more usable.

With ember-cli/ember-cli#8571 and  #617 (plus its many follow-on PRs #630 #636 #643 #645 #658 #669 #671 #672 and #681 ) having landed, is this functionally complete now?

Overall, it seems like this is what you're addressing with https://github.com/kellyselden/rfcs/blob/blueprints-update/text/0477-blueprints-update.md right @kellyselden?

Are there substantial deviations/missing pieces from what's described there? The main renaming piece I'm seeing is for this to be documented, but guessing there may still be other functionality needed before you consider this release-ready?

**Comment by kellyselden** [comment]
I'm still experimenting with the ideas in that RFC. That's why I haven't documented or advertised anything yet. You could probably get it to work by using `--from` and `--blueprint` together, but I would delete the resulting `ember-cli-update.json` because the file format is not stable yet.

**Comment by kellyselden** [comment]
Tracked in #812
