### ISSUE TITLE
Git hooks and ".git/index.lock" issues.

### ISSUE THREAD

**Issue by ruzz311** [ember-cli/ember-cli-update#586]
I see a few older issues for this project that revolve around commit hooks being a problem in the past.  All previous issues are closed but this issue still exists.

We use husky.js to populate commit hooks and I ran into this issue.  I'm not sure which one of the generated hooks are triggering this as it generates about every git hook you can think of. It could be pre-commit still.

**Version:** ember-cli-update@0.34.10

**Comment by ruzz311** [comment]
After a frustrating hour or so I was able to get around the issue by just renaming my hooks folder before running and putting it back when I was done.  Maybe this is how a fix can be implemented, but I'm not excited to have a package messing with my repo (but since this package already does a fair amount of operations with my repo, I guess its not any worse).  

Maybe it's time to remove git as a dependency to upgrade ember-cli?

**Comment by kellyselden** [comment]
I agree there's an issue, and I'm not sure the best fix.

> Maybe it's time to remove git as a dependency to upgrade ember-cli?

I don't think that's an option. The main purpose of this project is to do `git diff` and `git apply` for you.

**Comment by kellyselden** [comment]
For future me:

I got this trying to run ember-cli-update in `ember-cli-update\test\fixtures\codemod\latest-node\my-app`.

**Comment by kellyselden** [comment]
This probably isn't an issue anymore with v0.49.0.
