### ISSUE TITLE
Remove npm dependency (i.e. work with yarn)

### ISSUE THREAD

**Issue by jtrees** [ember-cli/ember-cli-update#589]
I would like to use this tool but it depends on npm. I have been able to do all my other ember-related work with yarn. It would be cool if ember-cli-update supported yarn too.

**Comment by kellyselden** [comment]
You can get yarn support by adding `"useYarn": true` to your "~/.ember-cli" file. Then run ember-cli-update with the `--create-custom-diff` option and it should give you a yarn diff. I'm working on making this better, but that's how it works today.
