### ISSUE TITLE
Force update

### ISSUE THREAD

**Issue by amk221** [ember-cli/ember-cli-update#639]
It would be great to be able to `ember-cli-update --force`. To skip the notification that "Tags match, nothing to apply"

**Comment by kellyselden** [comment]
What would be the desired outcome of a `--force` option? "Tags match, nothing to apply" should mean you are already on the latest version.

**Comment by amk221** [comment]
The use case is, I sometimes manually go through my addons an upgrade dependancies by hand. 

But, I want to make sure the addon is up to date (i.e. it has the relevant changes to the dotfiles etc, and other core cli files).

So, in order to run `ember-cli-update` I have to downgrade `ember-cli` in package.json, just so that I can run it.

Additionally, I may want to run the codemods _again_. But I can't if the version already matches. Without going through the downgrade rigmarole again.

Thoughts?

**Comment by kellyselden** [comment]
You can use the --from option instead of downgrading.

Also you can codemods multiple times on any version. Why would you need to downgrade?

**Comment by amk221** [comment]
I mean in order for `ember-cli-update` to run, I have to make the tags not-match, by downgrading.

...essentially I didn't realise that `--from` gives the behaviour I am after.
