### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mikeelemuel** [ember-cli/ember-cli-update#701]
If you are submitting a bug report, please run your command with the debug flag:

* Unix (global): `DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember-cli-update ...`
* Windows (global): `set DEBUG=ember-cli-update,boilerplate-update,git-diff-apply && ember-cli-update ...`
* Unix (command): `DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember update ...`
* Windows (command): `set DEBUG=ember-cli-update,boilerplate-update,git-diff-apply && ember update ...`

and post the console output in the block below:

```
No package.json was found in this directory
```

I was trying to update my ember-cli from `2.6.2` to `2.18` and below are the steps that I did:

Step 1: I ran the command `npm install -g ember-cli-update`
Step 2: I went to my ember project file and ran the `ember-cli-update --to 2.18`
Step 3: and below are the errors that I received
```
/usr/local/lib/node_modules/ember-cli-update/node_modules/klaw/src/index.js:53
      self.paths.push.apply(self.paths, pathItems)
                      ^

RangeError: Maximum call stack size exceeded
    at /usr/local/lib/node_modules/ember-cli-update/node_modules/klaw/src/index.js:53:23
    at go$readdir$cb (/usr/local/lib/node_modules/ember-cli-update/node_modules/graceful-fs/graceful-fs.js:187:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
``` 
Any response are much appreciated

**Comment by marc-outins** [comment]
I am having this exact same issue.

**Comment by kellyselden** [comment]
This probably isn't an issue anymore with v0.49.0.
