### ISSUE TITLE
Errors using ember-cli-update in Windows Sub System for Linux

### ISSUE THREAD

**Issue by therealbenhogan** [ember-cli/ember-cli-update#703]
Hi, 

I am running Windows10 and have Ubuntu 18.04 installed via WSL.

I wanted to test upgrading Ember and Ember-Cli on a project rather than upgrading Ember-Cli globally, so I ran

    ember install ember-cli-update --yarn

I have a clean git working directory, and then ran 

    ember update

When I do I get this error message which I'm struggling to fix:

    Command failed: git ls-files /mnt/c/Users/MyUsername/ember-projects/misc/ember-3-12-0/config/ember-cli-update.json
    fatal: /mnt/c/Users/Web: '/mnt/c/Users/Web' is outside repository

Many thanks in advance for any help you can provide here.

**Comment by kellyselden** [comment]
I'm not sure how to fix this mounted drive problem. Can you do the update outside of the WSL?

**Comment by therealbenhogan** [comment]
Hi Kelly - thanks for getting back. I don't believe so -I think I need to keep everything in the Linux environment (but I'm not an expert in WSL!).  I could try and perform a global update for ember-cli in WSL but thought it was safer to do this at the project level. Sorry for asking this - but if I update ember-cli globally can I specify an older version of Ember when I create a project (out of interest).

Many thanks

**Comment by kellyselden** [comment]
I was thinking that the linux mount usually is accessible from outside the environment in normal Windows. As some random directory. I think its normally not advisable to touch those files from Windows because they are Linux formatted, but I was curious if running the update on that project from outside gives you better results.

**Comment by therealbenhogan** [comment]
Hi - thanks for getting back. I don't believe that's possible. Can you let me know re the global update query above - if I can use an older version of Ember (if necessary) with the latest ember-cli I hope it would achieve what I'm after anyway?

**Comment by kellyselden** [comment]
You can mix and match like that.

**Comment by kellyselden** [comment]
Closing as I don't know how to progress this. Feel free to post any new info.
