### ISSUE TITLE
Maybe remove package-lock.json before npm install

### ISSUE THREAD

**Issue by jlami** [ember-cli/ember-cli-update#829]
I found that in some instances updating ember-cli seriously hurts performance of `ember s` and `ember build`. I traced this to the fact that package-lock.json holds back several packages if the old installed versions still satisfy the requirements. While this might be good to keep other addons stable, the performance penalty in our case was really bad.
When I removed **package-lock.json** and did `npm install` again, the `ember build` time went from 3+ minutes to 50 seconds.

Is it an option to always remove the package-lock.json before installing new packages?

ember-cli-update version used: 0.45.0

**Comment by kellyselden** [comment]
This would be outside the scope of this project. It only alters package.json. It doesn't run npm install/yarn install for you. It is up to the user how they want to do lockfiles.
