### ISSUE TITLE
Feature Idea: Detect yarn vs npm

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli-update#998]
It would be very nice to be able to detect whether the project this is being run against uses yarn or npm. This can cause issues right now where, for example, travis.yml gets mixed yarn/npm commands because some part of that file changed in the blueprint.

I know the outputs you're diffing against only use the default blueprint, but maybe ember-cli-update could detect that yarn is needed and then run the live blueprint instead of diffing against the output repo? Or if that's not feasible, at least some sort of console output to warn people?

Related: #125

**Comment by rwjblue** [comment]
Hmm, with the new blueprint config file setup I _think_ the iniital `--yarn` options to the first `ember new` / `ember addon` would be preserved...

**Comment by kellyselden** [comment]
A new version is about to be released, and the output repos are no longer used. This should use yarn appropriately.
